### ISSUE TITLE
tsc out of memory (10x memory increase) when importing @gluestack-ui/config

### ISSUE THREAD

**Issue by dbrekelmans** [gluestack/gluestack-ui#1663]
### Description

Compiling typescript runs out of memory when importing @gluestack-ui/config

### Steps to reproduce

In my Expo (react-native) project, when using the `GluestackUIProvider` provider, everything is fine.
When I pass the config from `@gluestack-ui/config` to the provider, suddenly my typescript compilation (`tsc` command) runs out of memory.

**Running normally**
```typescript
<GluestackUIProvider>
    <Slot/>
</GluestackUIProvider>
```

**Out of memory**
```typescript
import { config } from "@gluestack-ui/config"

//

<GluestackUIProvider config={ config }>
    <Slot/>
</GluestackUIProvider>
```

In my `package.json`, I've included these packages:
```
"@gluestack-style/react": "^1.0.41",
"@gluestack-ui/config": "^1.0.13",
"@gluestack-ui/themed": "^1.0.37",
```

I just installed the packages and then added the provider. I'm not using any of the actual components anywhere in my code.

### gluestack-ui Version

"@gluestack-style/react": "^1.0.41", "@gluestack-ui/config": "^1.0.13", "@gluestack-ui/themed": "^1.0.37"

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

Without importing `@gluestack-ui/config`
```
➜ NODE_OPTIONS=--max-old-space-size=4096 tsc --diagnostics --noEmit
Files:             1119
Lines:           176984
Identifiers:     197409
Symbols:         128732
Types:            11963
Instantiations:   27525
Memory used:    232183K
I/O read:         0.13s
I/O write:        0.00s
Parse time:       0.75s
Bind time:        0.18s
Check time:       0.22s
Emit time:        0.00s
Total time:       1.15s
```

Importing `@gluestack-ui/config`
```
➜ NODE_OPTIONS=--max-old-space-size=4096 tsc --diagnostics --noEmit
Files:              1305
Lines:           2530805
Identifiers:     2337418
Symbols:         2486422
Types:             11966
Instantiations:    27525
Memory used:    2989447K
I/O read:          0.34s
I/O write:         0.00s
Parse time:        6.82s
Bind time:         3.16s
Check time:        0.25s
Emit time:         0.00s
Total time:       10.22s
```

I'm increasing the allowed memory usage to 4GB to prevent an out of memory error and run the command succesfully.
Note that lines, identifiers, symbols, memory used and total time are all 10 times larger.

**Comment by ankit-tailor** [comment]
Hey @dbrekelmans, Thanks for reporting the issue. We're looking into it.

**Comment by ankit-tailor** [comment]
Hi Everyone, We have fixed the typescript memory leak issue. Please upgrade `@gluestack-style/react` and `@gluestack-ui/config` to latest version.

Getting below stats with the latest version.


```
tsc --diagnostics --noEmit
Files:              697
Lines:           148315
Identifiers:     133033
Symbols:         155092
Types:            12219
Instantiations:  411830
Memory used:    178340K
I/O read:         0.90s
I/O write:        0.00s
Parse time:       1.48s
Bind time:        0.17s
Check time:       0.58s
Emit time:        0.00s
Total time:       2.23s
```

**Comment by vyobukhov** [comment]
> Hi Everyone, We have fixed the typescript memory leak issue. Please upgrade `@gluestack-style/react` and `@gluestack-ui/config` to latest version.

Thank you, just wanted to share results (wow):
![telegram-cloud-photo-size-2-5298883311684408693-y](https://github.com/gluestack/gluestack-ui/assets/1265071/b9d85c15-4b59-4c17-a777-dcb9cbfd2572)

**Comment by ankit-tailor** [comment]
You can check this [PR](https://github.com/gluestack/gluestack-ui/pull/1693) for detailed stats ;)

**Comment by suhaotian** [comment]
Cool bro!

**Comment by nicolascavallin** [comment]
> Hi Everyone, We have fixed the typescript memory leak issue. Please upgrade `@gluestack-style/react` and `@gluestack-ui/config` to latest version.
> 
> Getting below stats with the latest version.
> 
> ```
> tsc --diagnostics --noEmit
> Files:              697
> Lines:           148315
> Identifiers:     133033
> Symbols:         155092
> Types:            12219
> Instantiations:  411830
> Memory used:    178340K
> I/O read:         0.90s
> I/O write:        0.00s
> Parse time:       1.48s
> Bind time:        0.17s
> Check time:       0.58s
> Emit time:        0.00s
> Total time:       2.23s
> ```

I've updated to the latest, but still having the same problem, and crashing the CI 🫠

**Comment by suhaotian** [comment]
```json
 "@gluestack-style/react": "1.0.48",
    "@gluestack-ui/config": "1.1.12",
    "@gluestack-ui/themed": "1.1.9",
```

These version is fine, but update to latest deps of gluestack-ui, the performance issue back!

@nicolascavallin Thanks for the feedback! @ankit-tailor Something break? I think add a test for performance is a good choice!

**Comment by nicolascavallin** [comment]
> ```json
>  "@gluestack-style/react": "1.0.48",
>     "@gluestack-ui/config": "1.1.12",
>     "@gluestack-ui/themed": "1.1.9",
> ```
> 
> These version is fine, but update to latest deps of gluestack-ui, the performance issue back!
> 
> @nicolascavallin Thanks for the feedback!
> 
> @ankit-tailor Something break? I think add a test for performance is a good choice!

Currently running

```
    "@gluestack-style/react": "^1.0.49",
    "@gluestack-ui/config": "1.1.12",
    "@gluestack-ui/themed": "^1.1.9",
```

and now seems working, but no with `1.1.16`.

Thanks @suhaotian

**Comment by ankit-tailor** [comment]
Hey @suhaotian and @nicolascavallin, Thanks for reporting the issue. We'll look into it and try to fix it ASAP. 

And yes @suhaotian surely, We'll need to setup some test cases for types. Because it's really difficult to manage such complex typing system. We'll plan it out for sure.

**Comment by ankit-tailor** [comment]
The issue fixed with latest version. config was published with incorrect version somehow.
