### ISSUE TITLE
Styles not being applied on a clean install

### ISSUE THREAD

**Issue by Viraj-10** [gluestack/gluestack-ui#2559]
### Discussed in https://github.com/gluestack/gluestack-ui/discussions/2526

<div type='discussions-op-text'>

<sup>Originally posted by **Wolvinny** October 23, 2024</sup>
Hi all.
First of all, i am very new to web development. I do have experience in typescript and node, but this is my first time touching web development, other than fooling around a little with React, so this might be a very simple fix but i've been stuck at this for over 6 hours at this point.
Currently, i am stuck on an issue, where i can import buttons and other components just fine, but they just wont be styled.

Following the [guide](https://gluestack.io/ui/docs/home/getting-started/installation), i first created an expo project (i am using, or well, trying to use react native)
After that, i ran the gluestack-ui init command and added a [button](https://gluestack.io/ui/docs/components/button) (yes, i also added it using the npx command). I also tried the manual installation but this only caused more issues.
Upon running the `npm start` command, and opening the web version, i am greeted with this error: `Unable to resolve module '@/global.css' from C:\Users\<>\app\app\_layout.tsx: '@/global.css' could not be found within the project or in these directories:
  node_modules`.
  This points to the lines 
  ```ts
  import "'@/global.css'";
import { GluestackUIProvider } from "@/'components/ui'/gluestack-ui-provider";
 ```
 which for some reason have additional ' in them (again, clean install, i did not change any code)
 
 After removing those; and restarting the web server, and running the following code.

```ts
import { Button, ButtonText } from "@/components/ui/button";
import React from "react";
import { View } from "react-native";

export default function Index() {
  return (
    <View
      style={{
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
      }}
    >
    
      <Button size="md" variant="solid" action="primary" >
          <ButtonText>Hello World!</ButtonText>
        </Button>
      
    </View>
  );
}
```
i get the following result: 
![image](https://github.com/user-attachments/assets/dbc08b4d-aa89-413f-b251-1a78f3792721)
None of the other components also render.
I am using Node v22.9.0; react v18.2.0 and expo SDK 51.0.38

I cannot make a snack (it freezes when i upload my code) or a sandbox (it does not allow me to upload any files),
but i feel this is a very simple issue that i cannot wrap my head around, nor have i seen someone with the same issue

Full `npm ls` output:
```
├── @babel/core@7.25.9
├── @expo/vector-icons@14.0.4
├── @gluestack-ui/button@1.0.7
├── @gluestack-ui/nativewind-utils@1.0.23
├── @gluestack-ui/overlay@0.1.15
├── @gluestack-ui/toast@1.0.7
├── @react-navigation/native@6.1.18
├── @types/jest@29.5.14
├── @types/react-test-renderer@18.3.0
├── @types/react@18.2.79
├── babel-plugin-module-resolver@5.0.2
├── expo-constants@16.0.2
├── expo-font@12.0.10
├── expo-linking@6.3.1
├── expo-router@3.5.23
├── expo-splash-screen@0.27.6
├── expo-status-bar@1.12.1
├── expo-system-ui@3.0.7
├── expo-web-browser@13.0.3
├── expo@51.0.38
├── jest-expo@51.0.4
├── jest@29.7.0
├── jscodeshift@0.15.2
├── nativewind@4.0.36
├── prettier@3.3.3
├── react-dom@18.2.0
├── react-native-gesture-handler@2.16.2
├── react-native-reanimated@3.10.1
├── react-native-safe-area-context@4.10.5
├── react-native-screens@3.31.1
├── react-native-svg@13.4.0
├── react-native-web@0.19.13
├── react-native@0.74.5
├── react-test-renderer@18.2.0
├── react@18.2.0
├── tailwindcss@3.4.14
└── typescript@5.3.3
```</div>

**Comment by gaofc** [comment]
I also followed the guide and the button didn't display. Has this problem been resolved?

**Comment by mithun-si** [comment]
I am experiencing the same issue in my Next.js project and also try to applying Tailwind utility classes to the button, there is no effect on its style.

**Comment by Viraj-10** [comment]
Hey @mithun-si , @JackGrantham @gaofc, Can you please share repo? and also which OS you are using `windows` or `mac`?

**Comment by mithun-si** [comment]
I'm using Windows

**Comment by mithun-si** [comment]
https://codesandbox.io/p/devbox/playaround-hpfszq

this is the my code sandbox link I think that you can get idea from there and also for your information I am using 
npx gluestack-ui@latest init
npx gluestack-ui@latest add --all
command to install gluestack-ui and it's components

**Comment by ryanmitchell** [comment]
I'm seeing the same issue in an Expo project. The components work but no styling is applied.

**Comment by vaibhk20** [comment]
Hey everyone! We've released an updated version of the CLI with bug fixes to address the reported issues. Let us know if you face any issues while using it.

**Comment by mithun-si** [comment]
Hi @vaibhk20, I am created fresh Next.js project and then install the latest gluestack-ui with this command "npx gluestack-ui@latest init" and try to used Button component but still the style is not applied 

Next.js version: 14.2.16

**Comment by Viraj-10** [comment]
Hey @mithun-si, Please add `"jsxImportSource": "nativewind"`  to your `tsconfig` file.

**Comment by JackGrantham** [comment]
I am still seeing the same issue.

Here are the steps I am taking:

1. run 'npx create-expo-app@latest --template' using the Blank Typescript template
2. run 'npm start' to make sure the application runs as expected
3. stop application and follow the gluestack-ui guide and start by running 'npx gluestack-ui init'
4. run 'npm start'
5. see issues with import of global.css and GluestackUIProvider
![gluestack_import_issue](https://github.com/user-attachments/assets/4c6c69af-5ee8-4f37-b283-4bf66ea21916)
6. Remove extra single quotes from both import statements
7. run 'npm start' ... application starts fine
8. stop application and run 'npx gluestack-ui add button'
9. add Button with ButtonText in App.tsx file making sure to import from './components/ui/button'
10. run 'npm start' ... see ButtonText but no styling

I also have tried adding "jsxImportSource": "nativewind" to my tsconfig file and this did not change anything for me.

**Comment by Viraj-10** [comment]
Hey @JackGrantham, I have created a [PR](https://github.com/JackGrantham/gluestackv2-test/pull/1) with all the fixes. Seems like cli is not working properly on windows.

**Comment by Viraj-10** [comment]
> I'm seeing the same issue in an Expo project. The components work but no styling is applied.

Hey @ryanmitchell, Can you checkout this [PR](https://github.com/JackGrantham/gluestackv2-test/pull/1) and try to make same changes to it for more detailed guide please have look at nativewind [docs](https://www.nativewind.dev/getting-started/expo-router).

**Comment by ryanmitchell** [comment]
Yeah thanks. I got it working by copying over the configs from the starter kit app.

**Comment by JackGrantham** [comment]
Thanks @Viraj-10 your changes worked. However, I did need to downgrade to Node v20 from v22 since I was running into issues with 'require' not being defined in some imports in tailwind.config.js and metro.config.js

**Comment by mithun-si** [comment]
Hey @Viraj-10 , After adding this "jsxImportSource": "nativewind" to mytsconfig file now I can use tailwindcss it's work thanks but the default behavior still not working for example
   <Button size="md" variant="outline" action="primary" >
          <ButtonText>Hello World!</ButtonText>
    </Button>
it should show a button with some outline right? but my case I only see the Hello World! text nothing else

Next.js: 14.2.16
windows: 11 pro

**Comment by Viraj-10** [comment]
> Hey @Viraj-10 , After adding this "jsxImportSource": "nativewind" to mytsconfig file now I can use tailwindcss it's work thanks but the default behavior still not working for example
> 
> ```
>   <Button size="md" variant="outline" action="primary" >
>       <ButtonText>Hello World!</ButtonText>
>     </Button>
> ```
> 
> it should show a button with some outline right? but my case I only see the Hello World! text nothing else
> 
> Next.js: 14.2.16 windows: 11 pro

@mithun-si please check your content property in `tailwind.config.js` file. give proper path to all the components and pages. checkout guide from tailwind [here](https://tailwindcss.com/docs/content-configuration#configuring-source-paths)

**Comment by mithun-si** [comment]
> > Hey @Viraj-10 , After adding this "jsxImportSource": "nativewind" to mytsconfig file now I can use tailwindcss it's work thanks but the default behavior still not working for example
> > ```
> >   <Button size="md" variant="outline" action="primary" >
> >       <ButtonText>Hello World!</ButtonText>
> >     </Button>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it should show a button with some outline right? but my case I only see the Hello World! text nothing else
> > Next.js: 14.2.16 windows: 11 pro
> 
> @mithun-si please check your content property in `tailwind.config.js` file. give proper path to all the components and pages. checkout guide from tailwind [here](https://tailwindcss.com/docs/content-configuration#configuring-source-paths)

Thanks @Viraj-10 it's working now but when I am building my Next.js application there is a lot's of type related warning and error and that's why application build is failed please solve this ASAP and  If I use
//@ts-ignore for where need type I can successfully build application so if I use //@ts-ignore is there any problem arise in future?

**Comment by miguel93041** [comment]
@Viraj-10 Any updates on when #2475 will be released? Nativewind 4.1 supposedly addresses https://github.com/nativewind/nativewind/issues/924, which has been a major hassle for both production and development.

**Comment by Viraj-10** [comment]
@miguel93041 you can install v4.1 with `--alpha` flag in CLI. 
we announced it yesterday on discord and [twitter](https://x.com/gluestack/status/1858877047747059731). 
![Uploading ray-so-export (1).png…]()

**Comment by Viraj-10** [comment]
@miguel93041 you can install v4.1 with `--alpha` flag in CLI. 
we announced it yesterday on discord and [twitter](https://x.com/gluestack/status/1858877047747059731). 


![ray-so-export (1)](https://github.com/user-attachments/assets/3021cffc-3e98-4240-8e7e-549b02d2405e)

**Comment by flyingL123** [comment]
> Seeing the same issue. Fresh expo react native app with no changes and follow the gluestack-ui guide both using CLI and manually and styles don't display.

@ryanmitchell did you ever get this working? I followed the instructions to try and start using gluestack in an existing expo project, but I can't get any styles to be applied to the components. Literally just trying to display a box from the documentation, but none of the styles are working. The component is rendered, but no styles.

**Comment by Viraj-10** [comment]
Hey @flyingL123, Please try this [repo](https://github.com/Viraj-10/expo-gluestack-ui). Let me know if it works for you. 
Also Please provide your repo as well.

**Comment by flyingL123** [comment]
@Viraj-10 yes the repo you provided does work for me. I copied all of the config files from your project to mine, but still no styles are applied. The only difference I notice is that both of our projects are using expo52, but your project uses the new architecture and mine does not. Is there any way that could possibly be causing the problem?

Unfortunately I can not share my repo because it's private, but I can try to make a minimal example to reproduce the problem if necessary.

**Comment by Viraj-10** [comment]
Hey @flyingL123, Even after disabling new arch it's working for me. Can you please try to reproduce this in similar repo?

**Comment by ryanmitchell** [comment]
@Viraj-10 I've just updated to Expo 52 and everything is broken again, no styles are being generated. I tried rolling back my changes but still no styles are generated. I cant figure out why.

I've tried different node versions (22, 21, 20) and lots of different configurations of tailwinds.config.js and metro.config.js and tsconfig.js.

Can I share the repo with you to see if you can see the issue?

**Comment by Viraj-10** [comment]
Hey @ryanmitchell, Please try this [documentation](https://geekyants.notion.site/Troubleshooting-Common-Issues-with-NativeWind-and-Why-You-Should-Try-gluestack-ui-14a1684eb349808e913ac7e9598488e6) otherwise please provide a repo so that we will be able to see the issue.

**Comment by ryanmitchell** [comment]
@Viraj-10 thanks for that, the changes to the metro.config.js file made the difference

**Comment by flyingL123** [comment]
@Viraj-10 - I noticed that the repo I am using, after following the instructions to install gluestack-ui, a `patches` directory was created with a patch file inside of it. I didn't create this myself and I see it does not exist in the working repo you created. Maybe that's the issue?

**Comment by flyingL123** [comment]
@Viraj-10 here is reproduction of my repo showing gluestack not working. I'm really not sure what else to do. Hope I'm missing something obvious you can point out. Thanks very much for you help.

https://github.com/flyingL123/gluestack-not-working

**Comment by Viraj-10** [comment]
Hey @flyingL123, I have created a [PR](https://github.com/dcatindoy/gluestack-expo-bug/pull/1) for your repo. Fixing issue with init. I have also updated all the components to latest version.

**Comment by flyingL123** [comment]
@Viraj-10 thank you. I still don't understand what I was doing wrong, but I'll take it. Appreciate the assistance.

**Comment by Viraj-10** [comment]
@flyingL123, There was a issue with version of `nativewind` and `react-native-css-interop`. Also `metro.config.js` was not correctly configured.

**Comment by franmarvega** [comment]
I have a similar issue. I am working in a React Native Expo project. I have installed gluestack/ui following all the steps from the official installation guide, I am able to add components but no styling is applied to them. I have tried some of the modifications suggested in previous coments, but the issue persists. This is my [Repo](https://github.com/franmarvega/villamarket_frontend). 

This is the output of `npm list`:

├── @babel/core@7.26.0
├── @gluestack-ui/button@1.0.8
├── @gluestack-ui/nativewind-utils@1.0.23
├── @gluestack-ui/overlay@0.1.16
├── @gluestack-ui/toast@1.0.8
├── @reduxjs/toolkit@2.3.0
├── @types/react@18.3.12
├── axios@1.7.8
├── babel-plugin-module-resolver@5.0.2
├── expo-status-bar@2.0.0
├── expo@52.0.11
├── jscodeshift@0.15.2
├── nativewind@4.1.23
├── react-devtools@6.0.1
├── react-native-css-interop@0.0.36
├── react-native-dotenv@3.4.11
├── react-native-reanimated@3.16.3
├── react-native-svg@15.8.0
├── react-native-web@0.19.13
├── react-native@0.76.3
├── react-redux@9.1.2
├── react@18.3.1
├── tailwindcss@3.4.15
└── typescript@5.7.2

**Comment by JavanPoirier** [comment]
For anyone who may have a similar issue with styles not being applied, make sure to check your `content` array in `tailwind.config.js`. I have a monorepo setup which differs and made it easy to forget this. See:

https://github.com/gluestack/gluestack-ui/issues/2612#issuecomment-2509520337

**Comment by Under-Warz** [comment]
Same issue here. I've double check tailwind configuration and it's working fine with react-native composant (Pressable, View...) but when I'm using the Button from gluestack, all the tailwind classes disappear. Only the nativewind classes remain.

I also try to use the storybook projects from exemple directory, they are not working...

PS : I have to use the nativewind@4.0.36 to be able to make tailwind working, with the last version, all my tailwind classes disappear on render

**Comment by arv07** [comment]
I have the same problem only in this case: I created this folder /src/login/ComponentName.tsx. so when I import this file from app/(login) styles are not apply, but if I moved ComponentName.tsx to /app folder, all styles are applied correctly.

**Comment by ziquanc** [comment]
I am having issue on my new RN Expo project, i refer this https://www.nativewind.dev/getting-started/expo-router and the last step import "../global.css"; then it works for me.

**Comment by fraction01** [comment]
I tried https://github.com/gluestack/gluestack-ui/issues/2559#issuecomment-2505453859 and was able to fix this by removing `"react-native-css-interop": "^0.0.36",` from `package.json` and `patches/react-native-css-interop+0.0.36.patch` file from the `patches` folder, then `npm i` and `npx expo start --clear`.

You can check the changes made by @Viraj-10 in this [PR](https://github.com/flyingL123/gluestack-not-working/pull/1) for other possible solutions.

Thanks @Viraj-10

**Comment by marcoaring** [comment]
> For anyone who may have a similar issue with styles not being applied, make sure to check your `content` array in `tailwind.config.js`. I have a monorepo setup which differs and made it easy to forget this. See:
> 
> [#2612 (comment)](https://github.com/gluestack/gluestack-ui/issues/2612#issuecomment-2509520337)

This work for me, thank you @JavanPoirier

**Comment by tech-sunvi** [comment]
After beating about the bush all day long, I noticed I didn't import `global.css` in my root `layout.tsx`. I'm on Expo

**Comment by fausantosdev** [comment]
> Para quem tiver um problema semelhante com estilos não aplicados, certifique-se de verificar seu `content`array em `tailwind.config.js`. Eu tenho uma configuração de monorepo que é diferente e facilitou o esquecimento disso. Veja:
> 
> [#2612 (comentário)](https://github.com/gluestack/gluestack-ui/issues/2612#issuecomment-2509520337)

This was the solution in my case.

**Comment by Sanchitv3** [comment]
Thanks for reporting!

This is no longer applicable with the current version of the codebase.

Closing for now, please open a new issue if it still persists 🙌
