### ISSUE TITLE
Expo 54 + gluestack-ui v3 starter → App crashes (Reanimated + Overlay components not working) - now app not working at all

### ISSUE THREAD

**Issue by MrAhmedElsayed** [gluestack/gluestack-ui#3200]
Hi gluestack team,

I’m building an Expo React Native app using **gluestack-ui v3**.
My project was \~70% complete when I upgraded to **Expo SDK 54** (as recommended).

After upgrade, I started facing **serious runtime errors** and my app is now broken.

---

### What I tried

* Followed the official Expo 54 upgrade steps.
* Fixed all warnings and rebuild issues.
* Tried with both my existing project and a **fresh project** using the **gluestack-ui v3 starter kit**.
* Removed `react-native-worklets` (suspecting conflict with Reanimated).
* Cleared caches (`expo prebuild --clean`, `expo start -c`).
* Ensured `import 'react-native-reanimated'` is at the top of entry file.
* Verified Babel config includes `react-native-reanimated/plugin`.
* Updated `tsconfig.json` with `"jsx": "react-jsx"`.

Still, **no overlay components work** (Drawers, Modals, Menus, Alerts, etc.) and I get runtime crashes.

---

### Error Example

```
ERROR  [Error: Exception in HostFunction: <unknown>]

Call Stack
  installTurboModule (<native>)
  constructor (node_modules\react-native-reanimated\src\worklets\WorkletsModule\NativeWorklets.ts)
  ...
```

---

### Environment

* **expo:** \~54.0.1
* **react-native:** 0.81.4
* **react-native-reanimated:** 3.17.5
* **nativewind:** ^4.1.23
* **@gluestack-ui/core:** ^3.0.0
* **expo-router:** \~6.0.0

---

### babel.config.js

```js
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      [
        'babel-preset-expo',
        { jsxImportSource: 'nativewind' },
      ],
      'nativewind/babel',
    ],
    plugins: [
      ['module-resolver', {
        root: ['./'],
        alias: {
          '@': './',
          'tailwind.config': './tailwind.config.js',
        },
      }],
      'react-native-reanimated/plugin',
    ],
  };
};
```

---

### package.json (relevant deps)

```json
"expo": "~54.0.1",
"react": "19.1.0",
"react-native": "0.81.4",
"react-native-reanimated": "3.17.5",
"nativewind": "^4.1.23",
"@gluestack-ui/core": "^3.0.0",
"expo-router": "~6.0.0"
```

---

### Expected

Overlay components (Drawer, Modal, Menu, Alert, etc.) should render correctly in Expo 54 as they did before upgrade.

### Actual

The app crashes on startup or overlays do not render at all.

---

Can you please confirm whether **gluestack-ui v3** is fully compatible with **Expo SDK 54** and **Reanimated 3.17.5**? If not, is there a workaround or patch?

Thanks 🙏

**Comment by vitofor** [comment]
hello, yes i have the same problem 

// in my terminal when i launch expo start //
Logs for your project will appear below. Press Ctrl+C to exit.
› Reloading apps
| [Reanimated] Seems like you are using a Babel plugin `react-native-reanimated/plugin`. It was moved to `react-native-worklets` package. Please use `react-native-worklets/plugin` instead.
| [Reanimated] Seems like you are using a Babel plugin `react-native-reanimated/plugin`. It was moved to `react-native-worklets` package. Please use `react-native-worklets/plugin` instead.
| [Reanimated] Seems like you are using a Babel plugin `react-native-reanimated/plugin`. It was moved to `react-native-worklets` package. Please use `react-native-worklets/plugin` instead.
| [Reanimated] Seems like you are using a Babel plugin `react-native-reanimated/plugin`. It was moved to `react-native-worklets` package. Please use `react-native-worklets/plugin` instead.
| [Reanimated] Seems like you are using a Babel plugin `react-native-reanimated/plugin`. It was moved to `react-native-worklets` package. Please use `react-native-worklets/plugin` instead.
| [Reanimated] Seems like you are using a Babel plugin `react-native-reanimated/plugin`. It was moved to `react-native-worklets` package. Please use `react-native-worklets/plugin` instead.
| [Reanimated] Seems like you are using a Babel plugin `react-native-reanimated/plugin`. It was moved to `react-native-worklets` package. Please use `react-native-worklets/plugin` instead.
| [Reanimated] Seems like you are using a Babel plugin `react-native-reanimated/plugin`. It was moved to `react-native-worklets` package. Please use `react-native-worklets/plugin` instead.
| [Reanimated] Seems like you are using a Babel plugin `react-native-reanimated/plugin`. It was moved to `react-native-worklets` package. Please use `react-native-worklets/plugin` instead.
| [Reanimated] Seems like you are using a Babel plugin `react-native-reanimated/plugin`. It was moved to `react-native-worklets` package. Please use `react-native-worklets/plugin` instead.
iOS Bundled 15200ms index.ts (3002 modules)
 WARN  SafeAreaView has been deprecated and will be removed in a future release. Please use 'react-native-safe-area-context' instead. See https://github.com/th3rdwave/react-native-safe-area-context

// actually for me it's just only warning / /

**Comment by feri-irawan** [comment]
@vitofor same error

This might be related
https://github.com/expo/expo/issues/38832

**Comment by MrAhmedElsayed** [comment]
## Why Expo 54 Broke My App

### 1. **Animation Library Conflicts**
The main culprit was `@legendapp/motion` - an animation library that became incompatible with Expo 54. Here's what happened:

- **Before Expo 54**: `@legendapp/motion` worked fine with your Gluestack UI components
- **After Expo 54**: The library's internal dependencies conflicted with React Native's new architecture and Metro bundler changes
- **Result**: All overlay components (Drawer, Modal, ActionSheet) stopped working because they relied on this animation library

### 2. **React Native Architecture Changes**
Expo 54 includes updates to React Native that changed:
- How animations are handled
- Component rendering pipeline
- Metro bundler configuration
- Native module compatibility

### 3. **Gluestack UI Dependencies**
Your Gluestack UI components were using:
- `@legendapp/motion` for animations
- Complex animation wrappers that broke with the new React Native version
- Dependencies that weren't updated for Expo 54 compatibility

**Comment by dvillegasGlobalis** [comment]
I am in the same boat, With gluestack v2 it happens the same, other libraries for modals, etc also are not working or with performance issues like react-native-modal that works but with very bad performance.  You are using reanimated 3, i am using reanimated 4 and still is not working.

**Comment by sebastianmusial** [comment]
Hello, I’m facing the same issue, and it’s breaking my app. I’d appreciate it if you could share any solutions or workarounds you discover.

**Comment by MrAhmedElsayed** [comment]
> Hello, I’m facing the same issue, and it’s breaking my app. I’d appreciate it if you could share any solutions or workarounds you discover.

I am not experienced enough to provide a solution for this significant problem. I used a cursor to direct the changes needed to resolve the issue, which did work, but in a rather poor way. The animation library was removed, and some changes were made that stopped the app from breaking; however, the app now behaves in a strange manner. 

Due to the deadline, I sacrificed some quality and rewrote the app's UI using Tamagui, but this is only a temporary fix. If you have the time, I trust that the Expo and Gluestack UI teams can resolve this issue, or perhaps someone brilliant from the community can find a solution. I wish I could be of more help.

**Comment by xinchen37** [comment]
I also encountered the same issue: Expo 54 + gluestack-ui v3 app crash

**Comment by tiagointerativa** [comment]
Estou enfrentando o mesmo problema com Expo 54 + Gluestack.

**Comment by t3db0t** [comment]
Same here, starting with a 100% clean create-expo-app build. Confirmed working before doing `npx gluestack-ui init`. Same errors as above. Spent hours on it and still no solution.

**Comment by alinakassym** [comment]
same issue: Expo 54 + gluestack-ui . All overlay components stopped working

**Comment by feri-irawan** [comment]
An issue has been opened in the official Reanimated repo. You might also want to subscribe to it.

https://github.com/software-mansion/react-native-reanimated/issues/8231

**Comment by Maltronic** [comment]
The existing `@legendapp/motion` animations are not compatible with Reanimated 4 and neither are some Nativewind v4 animation classNames. In most cases a workaround is to use Reanimated 4's built-in [layout transitions](https://docs.swmansion.com/react-native-reanimated/docs/layout-animations/entering-exiting-animations).

I've created PR #3204 which shows how to make the Modal & Select-Actionsheet components compatible with Reanimated 4 (for basic use-cases at least), just update your repo's gluestack-ui components:
- [src/components/ui/modal/index.tsx](https://github.com/gluestack/gluestack-ui/blob/bef5971cdafc7c92b46e0a9db4854f79e238e4c7/src/components/ui/modal/index.tsx)
- [src/components/ui/select/select-actionsheet.tsx](https://github.com/gluestack/gluestack-ui/blob/b9e4e1055ebb51d3d5f49801be9efbe5e2275b4a/src/components/ui/select/select-actionsheet.tsx)

Other affected components should be fixable with similar changes.

**Comment by fulutas** [comment]
On Expo 53 and experiencing the same. help me please.

**Comment by Anskyuan** [comment]
Hi guys, I am using Expo54 by `npx create-expo-app@latest`, then I added all gluestack ui componets of the latest version. Is this the same issue?
**Environment**
expo: ~54.0.6
react-native: 0.81.4
react-native-reanimated: ~4.1.0
nativewind: ^4.2.0
@gluestack-ui/core: ^3.0.6
expo-router: ~6.0.3

I wrote a simple Input component, it works well on web, but display not correctly in expo go iOS.
`import React, { useState } from 'react';
import { Input, InputField, InputIcon, InputSlot } from '@/components/ui/input';
import { Icon } from '@/components/ui/icon';
import { LockIcon, EyeIcon, EyeOffIcon } from '@/components/ui/icon';
import { Pressable } from '@/components/ui/pressable';

interface PasswordInputProps {
  placeholder?: string;
  value?: string;
  onChangeText?: (text: string) => void;
  className?: string;
}

export function PasswordInput({
  placeholder = 'Enter Password',
  value = '',
  onChangeText,
  className = '',
}: PasswordInputProps) {
  const [showPassword, setShowPassword] = useState(false);

  const handleTogglePassword = () => {
    setShowPassword(prev => !prev);
  };

  return (
    <Input
      variant='outline'
      className={`bg-[#F4F7FF] rounded-[12px] border-[#B2B4C1] ${className}`}
    >
      <InputSlot className='pl-4'>
        <InputIcon as={LockIcon} className='text-[#B2B4C1]' />
      </InputSlot>
      <InputField
        type={showPassword ? 'text' : 'password'}
        placeholder={placeholder}
        value={value}
        onChangeText={onChangeText}
        className='text-[#B2B4C1] text-base placeholder:text-[#B2B4C1] px-0 flex-1'
        placeholderTextColor='#B2B4C1'
      />
      <InputSlot className='pr-4'>
        <Pressable onPress={handleTogglePassword} className='p-1'>
          <Icon
            as={showPassword ? EyeOffIcon : EyeIcon}
            size='md'
            className='text-[#B2B4C1]'
          />
        </Pressable>
      </InputSlot>
    </Input>
  );
}
`
PC display:

<img width="1058" height="1596" alt="Image" src="https://github.com/user-attachments/assets/5f31aace-fba9-4ed0-ba4e-bf28c91b6ea7" />

Expo Go on iOS display:

![Image](https://github.com/user-attachments/assets/055c1a7d-0b65-4f86-960d-8c9f0a9cd3b4)

**Comment by Anskyuan** [comment]
> Same here, starting with a 100% clean create-expo-app build. Confirmed working before doing `npx gluestack-ui init`. Same errors as above. Spent hours on it and still no solution.

Me too, I just add a simple Input, but display not correctly

**Comment by MrAhmedElsayed** [comment]
## 📋 Reproduction Repository Available

I've created a complete reproduction repository that demonstrates this issue:

**Repository**: https://github.com/MrAhmedElsayed/gluestackv3-expo54

**README with full details**: https://github.com/MrAhmedElsayed/gluestackv3-expo54/blob/main/README.md

### Summary of findings:

**🚨 Issue Scope**: This affects **ALL overlay/animation components**, not just specific ones:
- Actionsheet ❌
- Drawer ❌  
- Modal ❌
- Alert Modal ❌
- Menu ❌
- Popover ❌

**🔧 Environment tested**:
- Fresh Expo SDK 54 project (`npx create-expo-app@latest`)
- Gluestack UI v3 (`npx gluestack-ui init` + `npx gluestack-ui add --all`)
- All recommended fixes applied (`expo-doctor`, `expo install --check`)
- Babel config updated to use `react-native-worklets/plugin`

**📋 Steps followed exactly**:
1. Official Gluestack installation docs
2. Fixed all dependency warnings
3. Updated babel.config.js as recommended by Reanimated warnings
4. Components load but are **completely non-functional** - no animations, no interactions

**💡 Temporary workaround**: The repo includes a working native Modal implementation as a temporary solution.

This appears to be a fundamental compatibility issue between `@legendapp/motion` (bundled with Gluestack UI v3) and Expo SDK 54's React Native 0.81 + React 19.1.0 environment.

**Comment by kurtakiv** [comment]
The same problem

**Comment by luizpcam** [comment]
The same problem here !

**Comment by amibug** [comment]
Me too, those compoents that depend on @legendapp/motion are not working.

**Comment by fulutas** [comment]
```
module.exports = function (api) {
  api.cache(true);
  const plugins = [];

  return {
    presets: [["babel-preset-expo", { jsxImportSource: "nativewind" }]],
    plugins,
  };
};
```

removing nativewind/babel from the presets list in babel.config.js solved the issue for me

**Comment by amibug** [comment]
> Hi gluestack team,
> 
> I’m building an Expo React Native app using **gluestack-ui v3**. My project was ~70% complete when I upgraded to **Expo SDK 54** (as recommended).
> 
> After upgrade, I started facing **serious runtime errors** and my app is now broken.
> 
> ### What I tried
> * Followed the official Expo 54 upgrade steps.
> * Fixed all warnings and rebuild issues.
> * Tried with both my existing project and a **fresh project** using the **gluestack-ui v3 starter kit**.
> * Removed `react-native-worklets` (suspecting conflict with Reanimated).
> * Cleared caches (`expo prebuild --clean`, `expo start -c`).
> * Ensured `import 'react-native-reanimated'` is at the top of entry file.
> * Verified Babel config includes `react-native-reanimated/plugin`.
> * Updated `tsconfig.json` with `"jsx": "react-jsx"`.
> 
> Still, **no overlay components work** (Drawers, Modals, Menus, Alerts, etc.) and I get runtime crashes.
> 
> ### Error Example
> ```
> ERROR  [Error: Exception in HostFunction: <unknown>]
> 
> Call Stack
>   installTurboModule (<native>)
>   constructor (node_modules\react-native-reanimated\src\worklets\WorkletsModule\NativeWorklets.ts)
>   ...
> ```
> 
> ### Environment
> * **expo:** ~54.0.1
> * **react-native:** 0.81.4
> * **react-native-reanimated:** 3.17.5
> * **nativewind:** ^4.1.23
> * **@gluestack-ui/core:** ^3.0.0
> * **expo-router:** ~6.0.0
> 
> ### babel.config.js
> module.exports = function (api) {
>   api.cache(true);
>   return {
>     presets: [
>       [
>         'babel-preset-expo',
>         { jsxImportSource: 'nativewind' },
>       ],
>       'nativewind/babel',
>     ],
>     plugins: [
>       ['module-resolver', {
>         root: ['./'],
>         alias: {
>           '@': './',
>           'tailwind.config': './tailwind.config.js',
>         },
>       }],
>       'react-native-reanimated/plugin',
>     ],
>   };
> };
> ### package.json (relevant deps)
> "expo": "~54.0.1",
> "react": "19.1.0",
> "react-native": "0.81.4",
> "react-native-reanimated": "3.17.5",
> "nativewind": "^4.1.23",
> "@gluestack-ui/core": "^3.0.0",
> "expo-router": "~6.0.0"
> ### Expected
> Overlay components (Drawer, Modal, Menu, Alert, etc.) should render correctly in Expo 54 as they did before upgrade.
> 
> ### Actual
> The app crashes on startup or overlays do not render at all.
> 
> Can you please confirm whether **gluestack-ui v3** is fully compatible with **Expo SDK 54** and **Reanimated 3.17.5**? If not, is there a workaround or patch?
> 
> Thanks 🙏

How can I use react-native-reanimated@3.17.5 in an Expo 54 project?
When I run the command `expo run:android`, the terminal reports an error and the Android app fails to build successfully.

Here is my package.json:
```
"dependencies": {
    "react-native-reanimated": "3.17.5"
  },
  "expo": {
    "install": {
      "exclude": [
        "react-native-reanimated@~4.0.1"
      ]
    }
  }
```

**Comment by Sanchitv3** [comment]
@MrAhmedElsayed @vitofor @feri-irawan @dvillegasGlobalis @sebastianmusial @xinchen37 @tiagointerativa @t3db0t @alinakassym @Maltronic @fulutas @Anskyuan @kurtakiv @luizpcam @amibug 
Thanks for reporting this 🙏
We hadn’t noticed the thread had so many comments. We’re looking into it now and will work on a fix soon.

**Comment by Sanchitv3** [comment]
Try the following upgrade steps to fix crashes with Expo 54 + Gluestack UI v3:
```
rm -rf node_modules
rm -rf .expo
rm -rf package-lock.json yarn.lock

yarn add @gluestack-ui/core@latest @gluestack-ui/utils@latest
npx expo install expo@latest --fix

yarn add react-native-reanimated
yarn add react-native-worklets

yarn start --reset-cache
```

This should resolve the Reanimated + Overlay issues.
> If you’re starting fresh, you can also init a new Expo app — it now works out of the box with Gluestack UI v3.

**Comment by Sanchitv3** [comment]
Let me know if anyone still runs into issues after this.

**Comment by tiagointerativa** [comment]
It work for me, thanks @Sanchitv3.

In case it helps someone, here are my files:

My babel.config.js
```typescript
module.exports = function (api) {
  api.cache(true);

  return {
    presets: [
      [
        'babel-preset-expo',
        {
          jsxImportSource: 'nativewind',
        },
      ],
      'nativewind/babel',
    ],

    plugins: [
      [
        'module-resolver',
        {
          root: ['./'],

          alias: {
            '@': './',
            'tailwind.config': './tailwind.config.js',
          },
        },
      ],
      'react-native-reanimated/plugin',
    ],
  };
};
```

And my package.json

```powershell
{
  "name": "app",
  "version": "1.0.0",
  "main": "index.ts",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/html-elements": "^0.10.1",
    "@gluestack-ui/core": "^3.0.10",
    "@gluestack-ui/provider": "^0.1.19",
    "@gluestack-ui/utils": "^3.0.7",
    "@legendapp/motion": "^2.4.0",
    "@react-navigation/native": "^7.1.17",
    "@react-navigation/native-stack": "^7.3.26",
    "babel-plugin-module-resolver": "^5.0.2",
    "expo": "^54.0.7",
    "expo-constants": "~18.0.8",
    "expo-image": "~3.0.8",
    "expo-linear-gradient": "~15.0.7",
    "expo-status-bar": "~3.0.8",
    "nativewind": "^4.1.23",
    "react": "19.1.0",
    "react-aria": "^3.43.1",
    "react-dom": "19.1.0",
    "react-native": "0.81.4",
    "react-native-animatable": "^1.4.0",
    "react-native-gesture-handler": "~2.28.0",
    "react-native-get-random-values": "~1.11.0",
    "react-native-reanimated": "~4.1.0",
    "react-native-safe-area-context": "~5.6.0",
    "react-native-screens": "~4.16.0",
    "react-native-svg": "15.12.1",
    "react-native-web": "^0.21.0",
    "react-native-worklets": "^0.5.1",
    "react-stately": "^3.41.0",
    "tailwind-variants": "^0.1.20",
    "tailwindcss": "^3.4.17"
  },
  "devDependencies": {
    "@types/react": "~19.1.0",
    "babel-preset-expo": "^54.0.0",
    "eas-cli": "^16.19.2",
    "typescript": "~5.9.2"
  },
  "private": true
}

```

**Comment by woopata** [comment]
> Try the following upgrade steps to fix crashes with Expo 54 + Gluestack UI v3:
> 
> ```
> rm -rf node_modules
> rm -rf .expo
> rm -rf package-lock.json yarn.lock
> 
> yarn add @gluestack-ui/core@latest @gluestack-ui/utils@latest
> npx expo install expo@latest --fix
> 
> yarn add react-native-reanimated
> yarn add react-native-worklets
> 
> yarn start --reset-cache
> ```
> 
> This should resolve the Reanimated + Overlay issues.
> 
> > If you’re starting fresh, you can also init a new Expo app — it now works out of the box with Gluestack UI v3.

works for me. thank you

**Comment by Calfur** [comment]
> 'react-native-reanimated/plugin',

this line should already be included in babel-preset-expo, does it also work without that @tiagointerativa ?

**Comment by J3tto** [comment]
Works here also.

**Comment by MrAhmedElsayed** [comment]
> Let me know if anyone still runs into issues after this.


Thanks a lot for looking into this 🙏

Could you please share the recommended Babel configuration file? Right now it’s a bit confusing — some of us are using react-native-reanimated, others are using the new react-native-worklets, and both seem to work. We’d like to know what the best practice configuration is going forward.

Also, could you please show how to use it inside _layout.tsx? At the moment I’m using react-native-reanimated, so an example setup would help a lot.

**Comment by kurtakiv** [comment]
@Sanchitv3 It’s not working for me, all my overlays open on the wrong rendered circle, for example drawer opens only on second click on the button

**Comment by Sanchitv3** [comment]
> > Let me know if anyone still runs into issues after this.
> 
> Thanks a lot for looking into this 🙏
> 
> Could you please share the recommended Babel configuration file? Right now it’s a bit confusing — some of us are using react-native-reanimated, others are using the new react-native-worklets, and both seem to work. We’d like to know what the best practice configuration is going forward.
> 
> Also, could you please show how to use it inside _layout.tsx? At the moment I’m using react-native-reanimated, so an example setup would help a lot.

Thanks a lot for checking this 🙏

The worklets issue actually comes from the react-native-reanimated side:
👉 https://github.com/software-mansion/react-native-reanimated/issues/8231

So if you’re running into this, it’s not a config problem in our setup but rather related upstream. For now, sticking with the standard react-native-reanimated setup in your Babel config is the safe path. Once the reanimated team resolves it, react-native-worklets should align better.

**Comment by kurtakiv** [comment]
It’s not working for me. After running all the commands, my UI breaks. I have to delete the entire `components/ui` directory and run `npx gluestack-ui@latest init` and` npx gluestack-ui@latest add --all`. After that the components are fixed, but overlays still don’t work. The console shows the component rendered, but nothing is visible in the UI unless I force a re-render by changing state.”

Package json
```
{
  "name": "app",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "reset-project": "node ./scripts/reset-project.js",
    "android": "DARK_MODE=media expo start --android",
    "ios": "DARK_MODE=media expo start --ios",
    "web": "DARK_MODE=media expo start --web",
    "lint": "expo lint"
  },
  "dependencies": {
    "@expo/html-elements": "0.12.5",
    "@expo/metro-runtime": "~6.1.2",
    "@expo/vector-icons": "^15.0.2",
    "@gluestack-ui/core": "^3.0.10",
    "@gluestack-ui/provider": "^0.1.19",
    "@gluestack-ui/utils": "^3.0.7",
    "@gluestack/ui-next-adapter": "^3.0.0",
    "@gorhom/bottom-sheet": "5.0.0-alpha.11",
    "@legendapp/motion": "2.4.0",
    "@react-native-async-storage/async-storage": "^2.1.2",
    "@react-navigation/bottom-tabs": "^7.3.10",
    "@react-navigation/elements": "^2.3.8",
    "@react-navigation/native": "^7.1.8",
    "babel-plugin-module-resolver": "^5.0.2",
    "expo": "^54.0.7",
    "expo-blur": "~15.0.7",
    "expo-clipboard": "~8.0.7",
    "expo-constants": "~18.0.8",
    "expo-font": "~14.0.8",
    "expo-haptics": "~15.0.7",
    "expo-image": "~3.0.8",
    "expo-linking": "~8.0.8",
    "expo-localization": "~17.0.7",
    "expo-router": "~6.0.5",
    "expo-splash-screen": "~31.0.10",
    "expo-sqlite": "~16.0.8",
    "expo-status-bar": "~3.0.8",
    "expo-symbols": "~1.0.7",
    "expo-system-ui": "~6.0.7",
    "expo-web-browser": "~15.0.7",
    "i18n-js": "^4.5.1",
    "lucide-react-native": "0.510.0",
    "nativewind": "4.1.23",
    "react": "19.1.0",
    "react-aria": "3.33.0",
    "react-dom": "19.1.0",
    "react-native": "0.81.4",
    "react-native-css-interop": "^0.1.22",
    "react-native-gesture-handler": "~2.28.0",
    "react-native-reanimated": "^4.1.0",
    "react-native-safe-area-context": "5.6.1",
    "react-native-screens": "~4.16.0",
    "react-native-svg": "15.12.0",
    "react-native-svg-transformer": "^1.5.1",
    "react-native-view-shot": "^4.0.3",
    "react-native-web": "^0.21.0",
    "react-native-webview": "13.15.0",
    "react-native-worklets": "^0.5.1",
    "react-native-worklets-core": "^1.6.2",
    "react-stately": "3.39.0",
    "tailwind-variants": "0.1.20",
    "tailwindcss": "3.4.17",
    "zustand": "^5.0.6"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@types/react": "~19.1.10",
    "eslint": "^9.25.0",
    "eslint-config-expo": "~10.0.0",
    "jscodeshift": "^0.15.2",
    "typescript": "~5.9.2"
  },
  "private": true
}
```

metro config
```
const { getDefaultConfig } = require('expo/metro-config');
const { withNativeWind } = require('nativewind/metro');

const config = getDefaultConfig(__dirname);
const { assetExts, sourceExts } = config.resolver;
config.resolver.assetExts = assetExts.filter((ext) => ext !== 'svg').concat(['wasm']);
config.resolver.sourceExts = [...sourceExts, 'svg'];


config.transformer = {
	...config.transformer,
	babelTransformerPath: require.resolve('react-native-svg-transformer'),
};
module.exports = withNativeWind(config, { input: './global.css' });
```

babel
```
module.exports = function (api) {
  api.cache(true);

  return {
    presets: [
      [
        'babel-preset-expo',
        {
          jsxImportSource: 'nativewind',
        },
      ],
      'nativewind/babel',
    ],

    plugins: [
      [
        'module-resolver',
        {
          root: ['./'],

          alias: {
            '@': './',
            'tailwind.config': './tailwind.config.js',
          },
        },
      ],
      'react-native-reanimated/plugin',
    ],
  };
};
```

**Comment by JordanHoang** [comment]
This:

> Try the following upgrade steps to fix crashes with Expo 54 + Gluestack UI v3:
> 
> ```
> rm -rf node_modules
> rm -rf .expo
> rm -rf package-lock.json yarn.lock
> 
> yarn add @gluestack-ui/core@latest @gluestack-ui/utils@latest
> npx expo install expo@latest --fix
> 
> yarn add react-native-reanimated
> yarn add react-native-worklets
> 
> yarn start --reset-cache
> ```
> 
> This should resolve the Reanimated + Overlay issues.
> 
> > If you’re starting fresh, you can also init a new Expo app — it now works out of the box with Gluestack UI v3.

plus this:

> ```
> module.exports = function (api) {
>   api.cache(true);
>   const plugins = [];
> 
>   return {
>     presets: [["babel-preset-expo", { jsxImportSource: "nativewind" }]],
>     plugins,
>   };
> };
> ```
> 
> removing nativewind/babel from the presets list in babel.config.js solved the issue for me

solved my issues with gluestack Select acting wonky

**Comment by kurtakiv** [comment]
`npx gluestack-ui@latest init` resets the  `@gluestack-ui/core` and `@gluestack-ui/utils` version to 3.0.0, 
@Sanchitv3 i guess it is not ok

**Comment by dudovcic** [comment]
Hi, I've upgraded to the latest versions ( @gluestack-ui/core 3.0.10 and @gluestack-ui/utils 3.0.7 ), removed the cache, reinstalled etc. - the app runs fine, but the animations seem broken, actionsheet doesn't show up immediately, only after I change screen ( when not supposed to show ) and without any animations.
I've tried refactoring actionsheet to use reanimated instead of @legendapp-motion, that definitely helps, but doesn't include all animations as in the original implementation when it worked.
Any experience with that ?

**Comment by luizpcam** [comment]
> Try the following upgrade steps to fix crashes with Expo 54 + Gluestack UI v3:
> 
> ```
> rm -rf node_modules
> rm -rf .expo
> rm -rf package-lock.json yarn.lock
> 
> yarn add @gluestack-ui/core@latest @gluestack-ui/utils@latest
> npx expo install expo@latest --fix
> 
> yarn add react-native-reanimated
> yarn add react-native-worklets
> 
> yarn start --reset-cache
> ```
> 
> This should resolve the Reanimated + Overlay issues.
> 
> > If you’re starting fresh, you can also init a new Expo app — it now works out of the box with Gluestack UI v3.

works for me, tks!

**Comment by luizpcam** [comment]
> > Try the following upgrade steps to fix crashes with Expo 54 + Gluestack UI v3:
> > ```
> > rm -rf node_modules
> > rm -rf .expo
> > rm -rf package-lock.json yarn.lock
> > 
> > yarn add @gluestack-ui/core@latest @gluestack-ui/utils@latest
> > npx expo install expo@latest --fix
> > 
> > yarn add react-native-reanimated
> > yarn add react-native-worklets
> > 
> > yarn start --reset-cache
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This should resolve the Reanimated + Overlay issues.
> > > If you’re starting fresh, you can also init a new Expo app — it now works out of the box with Gluestack UI v3.
> 
> works for me, tks!

I realized that SDK 54 wasn’t properly installed before, but after fixing that the issue with the modal still persists. Could you please check if there’s something else that might be causing it?

**Comment by NaveenPrajpati** [comment]
i have same issue i have upgrade every thing after that any styling not working, means tailwindcss not working

**Comment by Sanchitv3** [comment]
> Hi, I've upgraded to the latest versions ( @gluestack-ui/core 3.0.10 and @gluestack-ui/utils 3.0.7 ), removed the cache, reinstalled etc. - the app runs fine, but the animations seem broken, actionsheet doesn't show up immediately, only after I change screen ( when not supposed to show ) and without any animations.
> I've tried refactoring actionsheet to use reanimated instead of @legendapp-motion, that definitely helps, but doesn't include all animations as in the original implementation when it worked.
> Any experience with that ?

Can you please try reinstalling react-native-reanimated and following the setup guide here:
👉 https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started/

**Comment by Sanchitv3** [comment]
> `npx gluestack-ui@latest init` resets the `@gluestack-ui/core` and `@gluestack-ui/utils` version to 3.0.0,
> [@Sanchitv3](https://github.com/Sanchitv3) i guess it is not ok

make sure to clear lock files 
```rm -rf node_modules yarn.lock package-lock.json ``` 
I can confirm it’s pulling the latest version on my side — could you please retry running `npx gluestack-ui@latest init`?

**Comment by kurtakiv** [comment]
> Hi, I've upgraded to the latest versions ( @gluestack-ui/core 3.0.10 and @gluestack-ui/utils 3.0.7 ), removed the cache, reinstalled etc. - the app runs fine, but the animations seem broken, actionsheet doesn't show up immediately, only after I change screen ( when not supposed to show ) and without any animations. I've tried refactoring actionsheet to use reanimated instead of @legendapp-motion, that definitely helps, but doesn't include all animations as in the original implementation when it worked. Any experience with that ?

Had the same issue, 

upgrade  to `    "nativewind": "4.2.1",`
fixed  it

**Comment by Calfur** [comment]
Works on my side too.

I think updating "nativewind" to "4.2.1" was also required on my side.

Thanks @Sanchitv3  & @tiagointerativa

**Comment by Sanchitv3** [comment]
@NaveenPrajpati @luizpcam ...
If you’re seeing issues with styling, overlays, or animations after upgrading Gluestack UI (e.g., ActionSheet not showing correctly or animations broken), try updating nativewind to:
```
"nativewind": "4.2.1"
```

**Comment by luizpcam** [comment]
> [@NaveenPrajpati](https://github.com/NaveenPrajpati) [@luizpcam](https://github.com/luizpcam) ... If you’re seeing issues with styling, overlays, or animations after upgrading Gluestack UI (e.g., ActionSheet not showing correctly or animations broken), try updating nativewind to:
> 
> ```
> "nativewind": "4.2.1"
> ```

Tks @Sanchitv3 , now works like a charm!

**Comment by legassy** [comment]
@Sanchitv3  Thanks for this

> Try the following upgrade steps to fix crashes with Expo 54 + Gluestack UI v3:
> 
> ```
> rm -rf node_modules
> rm -rf .expo
> rm -rf package-lock.json yarn.lock
> 
> yarn add @gluestack-ui/core@latest @gluestack-ui/utils@latest
> npx expo install expo@latest --fix
> 
> yarn add react-native-reanimated
> yarn add react-native-worklets
> 
> yarn start --reset-cache
> ```
> 
> This should resolve the Reanimated + Overlay issues.
> 
> > If you’re starting fresh, you can also init a new Expo app — it now works out of the box with Gluestack UI v3.

and this 

> [@NaveenPrajpati](https://github.com/NaveenPrajpati) [@luizpcam](https://github.com/luizpcam) ... If you’re seeing issues with styling, overlays, or animations after upgrading Gluestack UI (e.g., ActionSheet not showing correctly or animations broken), try updating nativewind to:
> 
> ```
> "nativewind": "4.2.1"
> ```

but I don't know why I still have an issue with the drawer

**Comment by peterphanouvong** [comment]
If you're running into no styling issue after nativewind 4.2.1 upgrade, 
I managed to fix it with 
```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      ["babel-preset-expo", { jsxImportSource: "nativewind" }],
      "nativewind/babel",
    ],
    plugins: ["react-native-worklets/plugin"],
  };
};
```

and "react-native-css-interop": "^0.2.1"

**Comment by Sanchitv3** [comment]
> [@Sanchitv3](https://github.com/Sanchitv3) Thanks for this
> 
> > Try the following upgrade steps to fix crashes with Expo 54 + Gluestack UI v3:
> > ```
> > rm -rf node_modules
> > rm -rf .expo
> > rm -rf package-lock.json yarn.lock
> > 
> > yarn add @gluestack-ui/core@latest @gluestack-ui/utils@latest
> > npx expo install expo@latest --fix
> > 
> > yarn add react-native-reanimated
> > yarn add react-native-worklets
> > 
> > yarn start --reset-cache
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This should resolve the Reanimated + Overlay issues.
> > > If you’re starting fresh, you can also init a new Expo app — it now works out of the box with Gluestack UI v3.
> 
> and this
> 
> > [@NaveenPrajpati](https://github.com/NaveenPrajpati) [@luizpcam](https://github.com/luizpcam) ... If you’re seeing issues with styling, overlays, or animations after upgrading Gluestack UI (e.g., ActionSheet not showing correctly or animations broken), try updating nativewind to:
> > ```
> > "nativewind": "4.2.1"
> > ```
> 
> but I don't know why I still have an issue with the drawer

Can you please explain the drawer issue in a bit more detail, maybe in a sub-thread? That’ll help us reproduce and track it properly 🙌

**Comment by daniel-alsen** [comment]
It seems like a fresh install of Expo 54 (npx create-expo-app@latest) and Gluestack 3 (npx gluestack-ui init) is broken again unfortunately.

"expo": "^54.0.8"
"@gluestack-ui/core": "^3.0.10"
"@gluestack-ui/utils": "^3.0.7"
"nativewind": "^4.2.1"
"react-native-reanimated": "~4.1.0"
"react-native-worklets": "^0.5.1"
"@legendapp/motion": "^2.4.0"

**Comment by luizpcam** [comment]
> It seems like a fresh install of Expo 54 (npx create-expo-app@latest) and Gluestack 3 (npx gluestack-ui init) is broken again unfortunately.
> 
> "expo": "^54.0.8" "@gluestack-ui/core": "^3.0.10" "@gluestack-ui/utils": "^3.0.7" "nativewind": "^4.2.1" "react-native-reanimated": "~4.1.0" "react-native-worklets": "^0.5.1" "@legendapp/motion": "^2.4.0"

Yeah ... Same here!

**Comment by Sanchitv3** [comment]
@luizpcam @daniel-alsen 
Okay, I just tested it now — sometimes the fresh install skips adding the global.css import at the root layout. We’re aware of this and are working on a fix.

**Comment by daniel-alsen** [comment]
Thanks. It looks like it also adds the old reanimated embedded worklets plugin to the babel config?

**Comment by Sanchitv3** [comment]
@daniel-alsen ,
Good catch 🙌 — we’ll also update the Babel config to use `"react-native-worklets/plugin"` instead of `"react-native-reanimated/plugin"`.

That will remove the warning:
`[Reanimated] Seems like you are using a Babel plugin 'react-native-reanimated/plugin'. It was moved to 'react-native-worklets' package. Please use 'react-native-worklets/plugin' instead.`

**Comment by daniel-alsen** [comment]
There seems to be a final problem with React Native Reanimated that currently breaks a fresh new Gluestack project install with Expo (Using Parallax ScrollView in the example app). A fix seems to be on the way next week in Reanimated 4.1.1:

https://github.com/software-mansion/react-native-reanimated/pull/8227

**Comment by Sanchitv3** [comment]
> There seems to be a final problem with React Native Reanimated that currently breaks a fresh new Gluestack project install with Expo (Using Parallax ScrollView in the example app). A fix seems to be on the way next week in Reanimated 4.1.1:
> 
> [software-mansion/react-native-reanimated#8227](https://github.com/software-mansion/react-native-reanimated/pull/8227)

Oh, I didn’t get this issue on my side 🤔
Could you share a repro or steps to trigger it? That’ll help me check if it’s environment-specific or related to Parallax ScrollView.

**Comment by daniel-alsen** [comment]
You can just create an Empty Expo project, open it in Expo Go, and it will break:

npx create-expo-app@latest
npm install
npx expo start

If you have a development build, you will get a hard fault - EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000118 in EventPerformanceLogger.cpp (Crashlytics).

The issue is currently causing app crashes and a range of errors if you are importing Animated from 'react-native-reanimated', which many components do, including Gluestack (I would guess) and dependencies.

It's fixed by removing this If-statement from `packages/react-native-reanimated/src/animation/util.ts`:

`if (__DEV__ && ReducedMotionManager.jsValue) {
  logger.warn(
    Reduced motion setting is enabled on this device. This warning is visible only in the development mode. Some animations will be disabled by default. You can override the behavior for individual animations, see https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#reduced-motion-setting-is-enabled-on-this-device.
  );
}`

Then, the app won't crash as it renders and work, but the Gluestack / styling animation issues with Expo 54 / Reanimated 4 still remains to be fixed.

**Comment by daniel-alsen** [comment]
Just to clarify - What is Gluestack V3 and it's dependencies like Nativewind verified to work with now when it comes to the latest Expo? Can you please share a working package.json?

**Comment by Sanchitv3** [comment]
> Just to clarify - What is Gluestack V3 and it's dependencies like Nativewind verified to work with now when it comes to the latest Expo? Can you please share a working package.json?
```
{
  "name": "inittest",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "reset-project": "node ./scripts/reset-project.js",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "lint": "expo lint"
  },
  "dependencies": {
    "@expo/html-elements": "^0.10.1",
    "@expo/vector-icons": "^15.0.2",
    "@gluestack-ui/core": "^3.0.10",
    "@gluestack-ui/utils": "^3.0.7",
    "@legendapp/motion": "^2.4.0",
    "@react-navigation/bottom-tabs": "^7.4.0",
    "@react-navigation/elements": "^2.6.3",
    "@react-navigation/native": "^7.1.8",
    "babel-plugin-module-resolver": "^5.0.2",
    "expo": "~54.0.9",
    "expo-constants": "~18.0.9",
    "expo-font": "~14.0.8",
    "expo-haptics": "~15.0.7",
    "expo-image": "~3.0.8",
    "expo-linking": "~8.0.8",
    "expo-router": "~6.0.7",
    "expo-splash-screen": "~31.0.10",
    "expo-status-bar": "~3.0.8",
    "expo-symbols": "~1.0.7",
    "expo-system-ui": "~6.0.7",
    "expo-web-browser": "~15.0.7",
    "nativewind": "^4.2.1",
    "react": "19.1.0",
    "react-aria": "^3.43.2",
    "react-dom": "19.1.0",
    "react-native": "0.81.4",
    "react-native-gesture-handler": "~2.28.0",
    "react-native-reanimated": "~4.1.0",
    "react-native-safe-area-context": "^5.6.1",
    "react-native-screens": "~4.16.0",
    "react-native-svg": "^15.13.0",
    "react-native-web": "~0.21.0",
    "react-native-worklets": "^0.5.1",
    "react-stately": "^3.41.0",
    "tailwind-variants": "^0.1.20",
    "tailwindcss": "^3.4.17"
  },
  "devDependencies": {
    "@types/react": "~19.1.0",
    "eslint": "^9.25.0",
    "eslint-config-expo": "~10.0.0",
    "typescript": "~5.9.2"
  },
  "private": true
}
```
This is package.json of newly created expo-app with gluestack initialised in it.

**Comment by vladislav-gorovenko** [comment]
Seems like it is not compatible yet. Decided to stay on Expo 53 for now and use gluestack v.3 till gluestack is compatible with Expo 54.

**Comment by shujathaliirfan** [comment]
My react native application also got crashed due to upgrading to SDK 54 and Im using gluestack ui v3 and im half through the project if there is workaround please do let know

**Comment by vladislav-gorovenko** [comment]
> My react native application also got crashed due to upgrading to SDK 54 and Im using gluestack ui v3 and im half through the project if there is workaround please do let know

Just don’t upgrade to SDK 54. Use SDK 53 for now.

**Comment by shujathaliirfan** [comment]
> My react native application also got crashed due to upgrading to SDK 54 and Im using gluestack ui v3 and im half through the project if there is workaround please do let know

**Comment by shujathaliirfan** [comment]
Then what version should I use for react-native-animation

**Comment by Sanchitv3** [comment]
Hey folks,
This has already been fixed — can you please try again with the latest release? 
If you’re upgrading an existing **gluestack-ui** project to **Expo SDK 54**, here are the recommended troubleshooting steps:
```
rm -rf node_modules
rm -rf .expo
rm -rf package-lock.json yarn.lock

yarn add @gluestack-ui/core@latest @gluestack-ui/utils@latest
npx expo install expo@latest --fix

yarn add react-native-reanimated
yarn add react-native-worklets
yarn add react-native-css-interop@latest

yarn start --reset-cache
```
Also, please make sure you’re on the **latest version of NativeWind**.
Let us know if you’re still hitting issues after this 🙏

**Comment by feri-irawan** [comment]
> Hey folks,
> This has already been fixed — can you please try again with the latest release? 
> If you’re upgrading an existing **gluestack-ui** project to **Expo SDK 54**, here are the recommended troubleshooting steps:
> ```
> rm -rf node_modules
> rm -rf .expo
> rm -rf package-lock.json yarn.lock
> 
> yarn add @gluestack-ui/core@latest @gluestack-ui/utils@latest
> npx expo install expo@latest --fix
> 
> yarn add react-native-reanimated
> yarn add react-native-worklets
> 
> yarn start --reset-cache
> ```
> Also, please make sure you’re on the **latest version of NativeWind**.
> Let us know if you’re still hitting issues after this 🙏

This works for me. Yesterday, I did the same thing: set react-native-worklets/plugin in the Babel config.

**Comment by shujathaliirfan** [comment]
its not working for me 
i still get this warning message 
 SafeAreaView has been deprecated and will be removed in a future release. Please use 'react-native-safe-area-context' instead. See https://github.com/th3rdwave/react-native-safe-area-context

**Comment by daniel-alsen** [comment]
Thanks.

Are you sure this is working with all the component animations and the nativewind styling classNames? Nativewind v4 is not working well with Reanimated 4 and there are similar issues with Legendapp/Motion?

Last time I tried the setup you listed was a few days ago; All the styling was gone then and the animations did not work.

**Comment by vladislav-gorovenko** [comment]
> Hey folks, This has already been fixed — can you please try again with the latest release? If you’re upgrading an existing **gluestack-ui** project to **Expo SDK 54**, here are the recommended troubleshooting steps:
> 
> ```
> rm -rf node_modules
> rm -rf .expo
> rm -rf package-lock.json yarn.lock
> 
> yarn add @gluestack-ui/core@latest @gluestack-ui/utils@latest
> npx expo install expo@latest --fix
> 
> yarn add react-native-reanimated
> yarn add react-native-worklets
> 
> yarn start --reset-cache
> ```
> 
> Also, please make sure you’re on the **latest version of NativeWind**. Let us know if you’re still hitting issues after this 🙏

Hey, thanks. Works for me now!

**Comment by luizpcam** [comment]
After updating to SDK 54, all the styles in my app stopped working.

<img width="389" height="711" alt="Image" src="https://github.com/user-attachments/assets/37d37cfb-db72-4a09-8864-7b82266d619d" />

**Comment by vish404** [comment]
I think this has problem with create-react-app as well. I just updated my app to latest of rn@0.81.4 and gluestack-ui@3. The app stopped working. I am still investigating the problem.

I tried with fresh RN versions: 0.79.0 up so far. some has  `Cannot find module 'metro-react-native-babel-preset'`

**Comment by luizpcam** [comment]
@Sanchitv3 My app is finally working! Updating to the latest react-native-css-interop (^0.2.1) might have resolved the styling issue. In my package.json, I marked all the packages related to this issue for clarity.


```typescript
rm -rf node_modules
rm -rf .expo
rm -rf pnpm-lock.yaml

pnpm add @gluestack-ui/core@latest @gluestack-ui/utils@latest
npx expo install expo@latest --fix

pnpm add react-native-reanimated
pnpm add react-native-worklets

pnpm prebuild:clean
pnpm ios | android
``` 

```typescript
{
  "name": "gaplus",
  "version": "1.0.0",
  "main": "expo-router/entry",
  "license": "UNLICENSED",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "prebuild": "expo prebuild",
    "prebuild:clean": "expo prebuild --clean",
    "doctor": "npx expo-doctor",
    "watchman": "watchman watch-del '/Users/luizpcam/Dev/ga/gaplus' ; watchman watch-project '/Users/luizpcam/Dev/ga/gaplus'",
    "expo:fix": "npx expo install --fix",
    "upgrade-dependencies": "npx npm-check-updates -u",
    "lint": "eslint ."
  },
  "dependencies": {
    "@aws-sdk/client-s3": "^3.820.0",
    "@azure/core-asynciterator-polyfill": "^1.0.2",
    "@babel/runtime": "^7.27.0",
    "@expo/html-elements": "0.11.2",
    "@expo/vector-icons": "^15.0.2",
    "@gluestack-ui/core": "^3.0.10", <<- CHANGED THIS
    "@gluestack-ui/utils": "^3.0.7", <<- CHANGED THIS
    "@gluestack/ui-next-adapter": "^3.0.3",**
    "@hookform/resolvers": "^5.0.1",
    "@legendapp/motion": "^2.4.0",
    "@legendapp/state": "3.0.0-beta.30",
    "@op-engineering/op-sqlite": "^14.1.1",
    "@powersync/attachments": "^2.3.1",
    "@powersync/kysely-driver": "^1.3.0",
    "@powersync/op-sqlite": "^0.7.1",
    "@powersync/react-native": "^1.22.0",
    "@react-native-community/datetimepicker": "8.4.4",
    "@react-native-community/netinfo": "11.4.1",
    "@react-navigation/bottom-tabs": "^7.3.10",
    "@react-navigation/native-stack": "^7.3.10",
    "@supabase/supabase-js": "^2.49.9",
    "@types/lodash": "^4.17.16",
    "babel-plugin-module-resolver": "^5.0.2",
    "base64-arraybuffer": "^1.0.2",
    "clsx": "^2.1.1",
    "expo": "^54.0.10",
    "expo-asset": "~12.0.9",
    "expo-auth-session": "~7.0.8",
    "expo-build-properties": "~1.0.9",
    "expo-constants": "~18.0.9",
    "expo-dev-client": "~6.0.12",
    "expo-device": "~8.0.8",
    "expo-file-system": "^19.0.15",
    "expo-font": "~14.0.8",
    "expo-image": "~3.0.8",
    "expo-image-picker": "~17.0.8",
    "expo-linear-gradient": "~15.0.7",
    "expo-linking": "~8.0.8",
    "expo-navigation-bar": "^5.0.8",
    "expo-notifications": "~0.32.11",
    "expo-router": "^6.0.8",
    "expo-secure-store": "~15.0.7",
    "expo-splash-screen": "~31.0.10",
    "expo-status-bar": "~3.0.8",
    "expo-system-ui": "~6.0.7",
    "expo-task-manager": "~14.0.7",
    "expo-web-browser": "~15.0.7",
    "jwt-decode": "^4.0.0",
    "lodash": "^4.17.21",
    "mathjs": "^14.7.0",
    "moment": "^2.30.1",
    "nativewind": "^4.2.1", <<- CHANGED THIS
    "react": "19.1.0",
    "react-dom": "19.1.0",
    "react-hook-form": "^7.55.0",
    "react-native": "^0.81.4",
    "react-native-auth0": "^5.0.0-beta.1",
    "react-native-css-interop": "^0.2.1", <<- CHANGED THIS
    "react-native-edge-to-edge": "1.6.0",
    "react-native-gesture-handler": "~2.28.0",
    "react-native-get-random-values": "^1.11.0",
    "react-native-keyboard-controller": "^1.18.5",
    "react-native-mask-input": "^1.2.3",
    "react-native-mmkv": "^3.2.0",
    "react-native-modal-datetime-picker": "^18.0.0",
    "react-native-reanimated": "^4.1.0", <<- CHANGED THIS
    "react-native-safe-area-context": "~5.6.1",
    "react-native-screens": "~4.16.0",
    "react-native-svg": "15.12.1",
    "react-native-url-polyfill": "^2.0.0",
    "react-native-web": "^0.21.1",
    "react-native-webview": "~13.15.0",
    "react-native-worklets": "^0.5.1", <<- CHANGED THIS
    "tailwindcss": "^3.4.17",
    "uuid": "^11.1.0",
    "zod": "^3.24.2"
  },
  "devDependencies": {
    "@babel/core": "^7.26.10",
    "@babel/plugin-transform-async-generator-functions": "^7.26.8",
    "@types/node": "^22.14.1",
    "@types/react": "~19.1.13",
    "@types/uuid": "^10.0.0",
    "eslint": "^9.25.1",
    "eslint-config-expo": "^10.0.0",
    "eslint-config-prettier": "^10.1.2",
    "eslint-plugin-prettier": "^5.2.6",
    "jscodeshift": "17.3.0",
    "prettier": "^3.5.3",
    "react-devtools": "^6.1.1",
    "typescript": "~5.9.2"
  },
  "expo": {
    "doctor": {
      "reactNativeDirectoryCheck": {
        "enabled": true,
        "listUnknownPackages": false,
        "exclude": [
          "jwt-decode"
        ]
      }
    }
  },
  "private": true,
  "packageManager": "pnpm@10.17.1+sha512.17c560fca4867ae9473a3899ad84a88334914f379be46d455cbf92e5cf4b39d34985d452d2583baf19967fa76cb5c17bc9e245529d0b98745721aa7200ecaf7a"
}
```

**Comment by Samuelseidelc2518** [comment]
> [@Sanchitv3](https://github.com/Sanchitv3) My app is finally working! Updating to the latest react-native-css-interop (^0.2.1) might have resolved the styling issue. In my package.json, I marked all the packages related to this issue for clarity.
> 
> rm -rf node_modules
> rm -rf .expo
> rm -rf pnpm-lock.yaml
> 
> pnpm add @gluestack-ui/core@latest @gluestack-ui/utils@latest
> npx expo install expo@latest --fix
> 
> pnpm add react-native-reanimated
> pnpm add react-native-worklets
> 
> pnpm prebuild:clean
> pnpm ios | android
>  {
>   "name": "gaplus",
>   "version": "1.0.0",
>   "main": "expo-router/entry",
>   "license": "UNLICENSED",
>   "scripts": {
>     "start": "expo start",
>     "android": "expo run:android",
>     "ios": "expo run:ios",
>     "web": "expo start --web",
>     "prebuild": "expo prebuild",
>     "prebuild:clean": "expo prebuild --clean",
>     "doctor": "npx expo-doctor",
>     "watchman": "watchman watch-del '/Users/luizpcam/Dev/ga/gaplus' ; watchman watch-project '/Users/luizpcam/Dev/ga/gaplus'",
>     "expo:fix": "npx expo install --fix",
>     "upgrade-dependencies": "npx npm-check-updates -u",
>     "lint": "eslint ."
>   },
>   "dependencies": {
>     "@aws-sdk/client-s3": "^3.820.0",
>     "@azure/core-asynciterator-polyfill": "^1.0.2",
>     "@babel/runtime": "^7.27.0",
>     "@expo/html-elements": "0.11.2",
>     "@expo/vector-icons": "^15.0.2",
>     "@gluestack-ui/core": "^3.0.10", <<- CHANGED THIS
>     "@gluestack-ui/utils": "^3.0.7", <<- CHANGED THIS
>     "@gluestack/ui-next-adapter": "^3.0.3",**
>     "@hookform/resolvers": "^5.0.1",
>     "@legendapp/motion": "^2.4.0",
>     "@legendapp/state": "3.0.0-beta.30",
>     "@op-engineering/op-sqlite": "^14.1.1",
>     "@powersync/attachments": "^2.3.1",
>     "@powersync/kysely-driver": "^1.3.0",
>     "@powersync/op-sqlite": "^0.7.1",
>     "@powersync/react-native": "^1.22.0",
>     "@react-native-community/datetimepicker": "8.4.4",
>     "@react-native-community/netinfo": "11.4.1",
>     "@react-navigation/bottom-tabs": "^7.3.10",
>     "@react-navigation/native-stack": "^7.3.10",
>     "@supabase/supabase-js": "^2.49.9",
>     "@types/lodash": "^4.17.16",
>     "babel-plugin-module-resolver": "^5.0.2",
>     "base64-arraybuffer": "^1.0.2",
>     "clsx": "^2.1.1",
>     "expo": "^54.0.10",
>     "expo-asset": "~12.0.9",
>     "expo-auth-session": "~7.0.8",
>     "expo-build-properties": "~1.0.9",
>     "expo-constants": "~18.0.9",
>     "expo-dev-client": "~6.0.12",
>     "expo-device": "~8.0.8",
>     "expo-file-system": "^19.0.15",
>     "expo-font": "~14.0.8",
>     "expo-image": "~3.0.8",
>     "expo-image-picker": "~17.0.8",
>     "expo-linear-gradient": "~15.0.7",
>     "expo-linking": "~8.0.8",
>     "expo-navigation-bar": "^5.0.8",
>     "expo-notifications": "~0.32.11",
>     "expo-router": "^6.0.8",
>     "expo-secure-store": "~15.0.7",
>     "expo-splash-screen": "~31.0.10",
>     "expo-status-bar": "~3.0.8",
>     "expo-system-ui": "~6.0.7",
>     "expo-task-manager": "~14.0.7",
>     "expo-web-browser": "~15.0.7",
>     "jwt-decode": "^4.0.0",
>     "lodash": "^4.17.21",
>     "mathjs": "^14.7.0",
>     "moment": "^2.30.1",
>     "nativewind": "^4.2.1", <<- CHANGED THIS
>     "react": "19.1.0",
>     "react-dom": "19.1.0",
>     "react-hook-form": "^7.55.0",
>     "react-native": "^0.81.4",
>     "react-native-auth0": "^5.0.0-beta.1",
>     "react-native-css-interop": "^0.2.1", <<- CHANGED THIS
>     "react-native-edge-to-edge": "1.6.0",
>     "react-native-gesture-handler": "~2.28.0",
>     "react-native-get-random-values": "^1.11.0",
>     "react-native-keyboard-controller": "^1.18.5",
>     "react-native-mask-input": "^1.2.3",
>     "react-native-mmkv": "^3.2.0",
>     "react-native-modal-datetime-picker": "^18.0.0",
>     "react-native-reanimated": "^4.1.0", <<- CHANGED THIS
>     "react-native-safe-area-context": "~5.6.1",
>     "react-native-screens": "~4.16.0",
>     "react-native-svg": "15.12.1",
>     "react-native-url-polyfill": "^2.0.0",
>     "react-native-web": "^0.21.1",
>     "react-native-webview": "~13.15.0",
>     "react-native-worklets": "^0.5.1", <<- CHANGED THIS
>     "tailwindcss": "^3.4.17",
>     "uuid": "^11.1.0",
>     "zod": "^3.24.2"
>   },
>   "devDependencies": {
>     "@babel/core": "^7.26.10",
>     "@babel/plugin-transform-async-generator-functions": "^7.26.8",
>     "@types/node": "^22.14.1",
>     "@types/react": "~19.1.13",
>     "@types/uuid": "^10.0.0",
>     "eslint": "^9.25.1",
>     "eslint-config-expo": "^10.0.0",
>     "eslint-config-prettier": "^10.1.2",
>     "eslint-plugin-prettier": "^5.2.6",
>     "jscodeshift": "17.3.0",
>     "prettier": "^3.5.3",
>     "react-devtools": "^6.1.1",
>     "typescript": "~5.9.2"
>   },
>   "expo": {
>     "doctor": {
>       "reactNativeDirectoryCheck": {
>         "enabled": true,
>         "listUnknownPackages": false,
>         "exclude": [
>           "jwt-decode"
>         ]
>       }
>     }
>   },
>   "private": true,
>   "packageManager": "pnpm@10.17.1+sha512.17c560fca4867ae9473a3899ad84a88334914f379be46d455cbf92e5cf4b39d34985d452d2583baf19967fa76cb5c17bc9e245529d0b98745721aa7200ecaf7a"
> }

This worked for me. I just updated react-native-css-interop to ^0.2.1 and the styles is working now.

**Comment by lucasnovelo** [comment]
I am having a lot of type issues:
   Types of property 'size' are incompatible.
          Type 'string | number | undefined' is not assignable to type '"xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | "4xl" | "5xl" | undefined'.
            Type 'string' is not assignable to type '"xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | "4xl" | "5xl" | undefined'

Almost all the components are showing these typing issues.

It seems like  the new tva helper only accepts the literal tokens, the same happened with booleans such as sub, italic, highlight.

**Comment by paschalidi** [comment]
Updating to the ltest versions worked for me too

**Comment by Sanchitv3** [comment]
> I am having a lot of type issues: Types of property 'size' are incompatible. Type 'string | number | undefined' is not assignable to type '"xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | "4xl" | "5xl" | undefined'. Type 'string' is not assignable to type '"xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | "4xl" | "5xl" | undefined'
> 
> Almost all the components are showing these typing issues.
> 
> It seems like the new tva helper only accepts the literal tokens, the same happened with booleans such as sub, italic, highlight.

Got it, thanks for reporting this. We’ll look into it.

**Comment by michaeldev5** [comment]
Hello @Sanchitv3, I am having same type issues in text component.

```
Types of property 'size' are incompatible.
        Type 'string | number' is not assignable to type '"2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | "4xl" | "5xl" | "6xl"'.
```

**Comment by Sanchitv3** [comment]
Thanks for following up! We’re looking into the issue and will resolve it as soon as possible. Apologies for the delayed response — we’ve been heads-down building something exciting. Appreciate your patience!

**Comment by michaeldev5** [comment]
@Sanchitv3 Thank you. Appreciate the effort 🙏

**Comment by Sanchitv3** [comment]
This issue has been fixed — you can update to `@gluestack-ui/utils@3.0.11` to get the latest changes. Let us know if you run into anything else!

> I am having a lot of type issues: Types of property 'size' are incompatible. Type 'string | number | undefined' is not assignable to type '"xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | "4xl" | "5xl" | undefined'. Type 'string' is not assignable to type '"xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | "4xl" | "5xl" | undefined'
> 
> Almost all the components are showing these typing issues.
> 
> It seems like the new tva helper only accepts the literal tokens, the same happened with booleans such as sub, italic, highlight.

**Comment by luizpcam** [comment]
> This issue has been fixed — you can update to `@gluestack-ui/utils@3.0.11` to get the latest changes. Let us know if you run into anything else!
> 
> > I am having a lot of type issues: Types of property 'size' are incompatible. Type 'string | number | undefined' is not assignable to type '"xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | "4xl" | "5xl" | undefined'. Type 'string' is not assignable to type '"xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | "4xl" | "5xl" | undefined'
> > Almost all the components are showing these typing issues.
> > It seems like the new tva helper only accepts the literal tokens, the same happened with booleans such as sub, italic, highlight.

tks @Sanchitv3 ... worked here!
